name: Nextjs deploy production

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: 21.7.3
                  cache: 'npm'

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: |
                      docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
                      docker pull trunganh312/twitter:v4
                      docker stop twitter-clone
                      docker rm twitter-clone
                      docker run -dp 3000:3000 --restart unless-stopped --name twitter-clone -v ~/twitter-clone/uploads:/app/uploads trunganh312/twitter:v4
